apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      initContainers:
        - name: vault
          image: 'vault:1.0.1'
          args: ["agent", "-config=/etc/vault/agent-config.hcl"]
